version: "3.3"
services:
  db:
    image: apache/age:PG11_latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agens
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432