name: JDBC Driver Tests

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'drivers/jdbc/**'
      
  pull_request:
    branches: [ "master" ]
    paths: 
      - 'drivers/jdbc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        distributions: ['zulu', 'temurin', 'microsoft']

    defaults:
      run:
        working-directory: drivers/jdbc

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distributions }}
        java-version: '17'

    - name: Build and Test
      run: gradle build