on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest commit id of PostgreSQL 12
        run: |
          echo "PG_COMMIT_HASH=$(git ls-remote git://git.postgresql.org/git/postgresql.git refs/heads/REL_12_STABLE | awk '{print $1}')" >> $GITHUB_ENV

      - name: Cache PostgreSQL 12
        uses: actions/cache@v3
        id: pg12cache
        with:
          path: ~/pg12
          key: ${{ runner.os }}-v1-pg12-${{ env.PG_COMMIT_HASH }}

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        if: steps.pg12cache.outputs.cache-hit != 'true'
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y git gcc build-essential libreadline-dev zlib1g-dev flex bison

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            git clone --depth 1 --branch REL_12_STABLE git://git.postgresql.org/git/postgresql.git ~/pg12source
            cd ~/pg12source
            ./configure --prefix=$HOME/pg12 CFLAGS="-std=gnu99 -ggdb -O0" --enable-cassert
            make install -j$(nproc)

      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          run: |
            export PG_CONFIG=$HOME/pg12/bin/pg_config 
            make -j$(nproc)
            make install
            make installcheck
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          uname -a
          echo $(pwd)