name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          stale-issue-label: Abondoned
          stale-pr-label: Abondoned
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10


# Required Info:
# 1. number of days before the first notice
# 2. additional number of days before the issue/PR is closed.
# 3. 1 and 2 required for both issues and PRs
# 4. Should we ignore the issues/PRs created before a specific date? Because if we don't, the workflow will add stale comment to many issues/PRs that are already stale.
# 5. For some issues/PRs, we can have a specific label that will prevent the workflow from adding stale comments. Should we add it?